services:
  - mariadb

stages:
  - build
  - test
  - deploy

node-build:
  stage: build
  image: node:current-alpine3.10
  cache:
    paths:
      - $CI_PROJECT_DIR/.cache/npm
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.cache/npm
  script:
    - cd react-front-end
    - npm ci --cache $CI_PROJECT_DIR/.cache/npm --prefer-offline
    - npm run build

rust-build:
  stage: build
  image: rust:alpine
  cache:
    paths:
      - actix/cargo/
      - actix/target/
  before_script:
    - apk update
    - apk add openssl-dev
    - apk add build-base
    - apk add pkgconfig
    - apk add mariadb-client

  script:
    - cd actix
    - export DATABASE_URL=mysql://root:pass@mariadb/cs3099user-b5_project
    - mysql --user=root --password=pass -h mariadb --protocol=tcp cs3099user-b5_project < sql/schema.sql
    - cargo check

deploy_staging:
  stage: deploy
  environment:
    name: staging
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - chmod 600 .ssh/id_rsa
    - ssh-add .ssh/id_rsa
    - mkdir -p .ssh
    - chmod 700 .ssh
  script:
    - ssh -o "StrictHostKeyChecking=no" cs3099user-b5@cs3099user-b5.host.cs.st-andrews.ac.uk "cd Documents/project-code && git checkout master && git pull origin master && sh tmux.sh"
  only:
    - master

variables:
    MYSQL_DATABASE: "cs3099user-b5_project"
    MYSQL_ROOT_PASSWORD: "pass"
    MYSQL_PASSWORD: "123"
    CARGO_HOME: $CI_PROJECT_DIR/actix/cargo