services:
  - mysql

stages:
  - build
  - test
  - deploy

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cd actix
    - DATABASE_URL=mysql://runner:123@runner/test
    - apt update -y
    - apt-get install -y mariadb-client
    - mysql --user=runner --password=password -h mysql test < sql/schema.sql
    - cargo build --verbose
    - cargo test --verbose

node-latest:
  stage: build
  image: node:latest
  script:
    - cd react-front-end
    - npm install
    - npm run

variables:
    MYSQL_DATABASE: "test"
    MYSQL_ROOT_PASSWORD: "password"
    SSH_PRIVATE_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEA3mcMK+6b0xQJsX2BzfaoqOqJd9WRJWSuAU8ozFBsUrQqtJjFfA4ZXv1x8gpXPkwunQCuTHUecJpqrBZdJ/hh5loIL6j2seoNWS+kdcq00xvhw2bYODdcxRGW7DTNViUvOGvbVumVhRuTVXx0DJKrTD2nmVPLzVdwjjoUPNo+nQS4XHhfjPtMqTSc1d7rPOYftgFQv5hbF3C+f3BCLeDqTbyvzQCUNqItukLoHErvHedDPn5se7a7cnL4f8OKuUvT+WQSUF2/68TSbYycUgpz+ELACPlC5OdmV3UxX/cH75oCpf6BS5/YTzrMTX5mMd/oenlVSCssq1RBHBwpQj8orPMrkJ4eMcINtH09Bw+O8CDpp1pMgKH76ULZhIi7eNUg/06geeahV52H571v/aPfvSQeSmKonk8b/ncxWXeq+XvSbthPDv6AL97tI1Ko2Mdod3jJBh94PHdCJFyhwSRt39IusShowWIU8IOTAn7AkNn0zTXrLpXR78f35nst8SelAAAFkG5kfQBuZH0AAAAAB3NzaC1yc2EAAAGBAN5nDCvum9MUCbF9gc32qKjqiXfVkSVkrgFPKMxQbFK0KrSYxXwOGV79cfIKVz5MLp0Arkx1HnCaaqwWXSf4YeZaCC+o9rHqDVkvpHXKtNMb4cNm2Dg3XMURluw0zVYlLzhr21bplYUbk1V8dAySq0w9p5lTy81XcI46FDzaPp0EuFx4X4z7TKk0nNXe6zzmH7YBUL+YWxdwvn9wQi3g6k28r80AlDaiLbpC6BxK7x3nQz5+bHu2u3Jy+H/DirlL0/lkElBdv+vE0m2MnFIKc/hCwAj5QuTnZld1MV/3B++aAqX+gUuf2E86zE1+ZjHf6Hp5VUgrLKtUQRwcKUI/KKzzK5CeHjHCDbR9PQcPjvAg6adaTICh++lC2YSIu3jVIP9OoHnmoVedh+e9b/2j370kHkpiqJ5PG/53MVl3qvl70m7YTw7+gC/e7SNSqNjHaHd4yQYfeDx3QiRcocEkbd/SLrEoaMFiFPCDkwJ+wJDZ9M016y6V0e/H9+Z7LfEnpQAAAAMBAAEAAAGBALHkkRrO1/tFat96uYpKguvh9iVRQbE8T+aiL8sFhS++Bu6/yC8LhAW0CiGFXfVpsFtLASANClUdXrfZh5gCGCTN3QBqUTFMOnMdJZpGks7N3Y6Tw91rgxvqjuLO9XOzeIrT0vU5D60Ruo7FZnnsE3J/WoDNQxYzm8dX83odQ7oK3YCxlBRLqi0p9U0o6taiZ7kIYlNuhWZBe06qN3VFE4UsqR38GZF9tb/n5otC8PLlWacyLoniRxsrlVN00JCYci6SpIbBJZLhObSricQGKFG2mcWfrBxKp4aLX1InIXF5rxdynxvuf75uYI6qYtUx58fK9t63yReYiYf3Gd2cROMf7MlpxpuRlmr0icg8dN49+ff6qWfvARbiukgvsuUSsQDrIOP5Hc18hKLA6rDevm0aBHGiSJMGijEOp70mdLRahUVXROzcMQ/JBxIkLEPL+buSu9OXTgDUu3Qocfb5YynP21+TLS1j4AttMhRID3+Sc/3QWg04DCOD1ehACDGdYQAAAMBbgzY83qWRxZAo8/6lTJrnl8k7bi9zuKAP/q/Vfs2xatavt/bjF3r1bUAfGzSBtHYUoklvMdclOY8HJ39ZfhnBuAip9uebDP9crKIyFSonMHjR24qReL4d9hpQrhKaAML86QxbD50sRWg6dRx9y73h9fdBalAKyQqr/suKzl0XKaP5m9SFKWbanqTBhlfqOBGgGcOzAKqyDMuALdYc1AHAvHZAjIp5olDzIh90RkfYi2UE8lJw7BlZRmNpNYYnxl0AAADBAPSKdI4xSlKiHVYp0WQ+D93uIBrt2uZX+zt1FghQ1AVMHj7kzanQLQ+O9gGeWlfLd0/m9LiB0C4uCBv83dVBK6oKlS+t7Bdn4seQbvhJlVJjg0DytzBxKJtN3jiHHElY7ukQB4taCqzr1+pRHpHb5MA7izFITPo8327nDojwXoTUFY4VXu/KlkX50oD8lYpNAoDaE7eAipcm8YowF3VjqKQ9Jo+7/ZJIRx+3t3RAUayFQNlfbbrxg9LdSy1vf5fMCQAAAMEA6NMEohhlbHyCB5JismA5TdywAWBWT66NRg2WBipI81kT3r5d9RtUyTcsnhv/wySlUG9jZmq4ly4tZQ1ZNCCndahxS9pwf4xHGdHR27M7RZ388LGP5j2HAnBViQz4hCwwMaj5+N45DmAVOrB19fBy6Ks/1J4XJdOJJrvVu9YEYqYFSDEzvR3IKyN6MIOviTdVv1EE2T6LO2VcjEQjCovYy5P9m/umMuPh9+/MStDwvzxZ0hJGZZTlVDkQLjn4Tp29AAAAFGNzMzA5OXVzZXItYjVAdHJlbmNvAQIDBAUG-----END OPENSSH PRIVATE KEY-----"