#services:
#  - mariadb

stages:
  - build
  - test
  - deploy

#rust-build:
#  stage: build
#  image: rust:latest
#  script:
#    - cd actix
#    - export DATABASE_URL=mysql://root:pass@mariadb/cs3099user-b5_project
#    - apt update -y
#    - apt-get install -y mariadb-client
#    - mysql --user=root --password=pass -h mariadb --protocol=tcp cs3099user-b5_project < sql/schema.sql
#    - cargo build --verbose
#    - cargo test --verbose

#node-build:
#  stage: build
#  image: node:current-alpine3.10
#  script:
#    - cd react-front-end
#    - npm install
#    - npm run build

deploy_staging:
  type: deploy
  environment:
    name: staging
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 600 .ssh/id_rsa
    - ssh-add .ssh/id_rsa
    - mkdir -p .ssh
    - chmod 700 .ssh
  script:
    - ssh -o "StrictHostKeyChecking=no" cs3099user-b5@cs3099user-b5.host.cs.st-andrews.ac.uk "cd Documents/project-code && git checkout master && git pull origin master && exit"
  only:
    - master

variables:
    MYSQL_DATABASE: "cs3099user-b5_project"
    MYSQL_ROOT_PASSWORD: "pass"
    MYSQL_PASSWORD: "123"