stages:
  - build
  - test
  - deploy

node-build:
  stage: build
  image: node:current-alpine3.10
  cache:
    key: cs3099user-b5
    paths:
      - $CI_PROJECT_DIR/.cache/npm
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.cache/npm
  script:
    - cd frontend
    - npm ci --cache $CI_PROJECT_DIR/.cache/npm --prefer-offline
    - npm run build

rust-build:
  stage: build
  image: rust:alpine
  cache:
    key: cs3099user-b5
    paths:
      - backend/cargo/
      - backend/target/
  before_script:
    - apk update
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - chmod 600 .ssh/id_rsa
    - ssh-add .ssh/id_rsa
    - mkdir -p .ssh
    - chmod 700 .ssh
    - apk add openssl-dev
    - apk add build-base
    - apk add pkgconfig
    - apk add mariadb-client
    - rustup component add clippy

  script:
    - cd backend
    - ssh -f cs3099user-b5@cs3099user-b5.cs.st-andrews.ac.uk -L 21463:localhost:21463 -N
    - cargo clippy --all-targets --all-features -- -D warnings

deploy_staging:
  stage: deploy
  image: alpine:latest
  environment:
    name: staging
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - chmod 600 .ssh/id_rsa
    - ssh-add .ssh/id_rsa
    - mkdir -p .ssh
    - chmod 700 .ssh
  script:
    - ssh -o "StrictHostKeyChecking=no" cs3099user-b5@cs3099user-b5.host.cs.st-andrews.ac.uk "cd Documents/project-code && git checkout master && git pull origin master && sh tmux.sh"
  only:
    - master

variables:
    MYSQL_DATABASE: "cs3099user-b5_project"
    MYSQL_ROOT_PASSWORD: "pass"
    MYSQL_PASSWORD: "123"
    CARGO_HOME: $CI_PROJECT_DIR/actix/cargo